base:
    show_state: false
    template:
    - state_engine
    variables:
        active_color: orange
        max_height: false
        on_state: ''
    styles:
      grid:
      - grid-template-areas: '"i es" "n n" "space space" "cs cs"'
      - grid-template-columns: 1fr min-content
      - grid-template-rows: min-content min-content 1fr min-content
      card:
      - z-index: 0
      - background: "[[[ return states[entity.entity_id].state == 'on' || states[entity.entity_id].state == variables.on_state ? 'var(--' + variables.active_color + ')' : 'var(--contrast6)'; ]]]"
      - padding: 16px
      - '--mdc-ripple-press-opacity': 0
      - height: "[[[ return variables.max_height ? '100%' : '100px'; ]]]"
      img_cell:
      - z-index: 1
      - justify-self: start
      - width: 24px
      - height: 24px
      - line-height: 24px
      - border-radius: 8px
      icon:
      - z-index: 2
      - width: 24px
      - height: 24px
      - line-height: 24px
      - color: "[[[ return states[entity.entity_id].state == 'on' || states[entity.entity_id].state == variables.on_state ? 'var(--black)' : 'var(--contrast18)'; ]]]"
      name:
      - z-index: 3
      - text-align: start
      - white-space: no-wrap
      - font-weight: 50
      - justify-self: start
      - font-size: 12px
      - margin: 6px 0 2px 0
      - color: "[[[ return states[entity.entity_id].state == 'on' || states[entity.entity_id].state == variables.on_state ? 'var(--black)' : 'var(--contrast18)'; ]]]"
      - text-overflow: ellipsis
      custom_fields:
        cs:
        - text-align: left
        - white-space: "[[[ return variables.max_height ? 'normal' : 'no_wrap'; ]]]"
        - z-index: 4
        - justify-self: start
        - font-size: 12px
        - font-weight: 900
        - line-height: 16px
        - width: 100%
        - color: "[[[ return states[entity.entity_id].state == 'on' || states[entity.entity_id].state == variables.on_state ? 'var(--black)' : 'var(--contrast10)'; ]]]"
        es:
        - min-width: 12px
        - z-index: 5
        - justify-self: end
        - font-size: 12px
        - height: "16px"
        - border-radius: 16px
        - padding: 2px 4px 2px 4px
        - background: var(--darker)
        - color: "[[[ return states[entity.entity_id].state == 'on' || states[entity.entity_id].state == variables.on_state ? 'var(--black)' : 'var(--contrast10)'; ]]]"
    style: |
      ha-card {
        transition: 300ms !important;
      }